In [1]:
import pandas as pd
import numpy as np

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.44)

array([2.44, 2.44, 2.44, 2.44, 2.44, 2.44, 2.44, 2.44, 2.44, 2.44])

In [5]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [8]:
arr = np.array([1,2,3,4,5])

In [9]:
print(arr)
arr[3]=7
print(arr)

[1 2 3 4 5]
[1 2 3 7 5]

In [10]:
arr = np.zeros((3,5))

In [11]:
print(arr)
arr[0,0]=10
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[10.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

In [12]:
arr[:,2]=[1,1,1]
print(arr)

[[10.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]]

In [14]:
arr[2] = [5,5,5,5,5]
print(arr)

[[10.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 5.  5.  5.  5.  5.]]

In [15]:
#random arrays
np.random.rand(3,5)

array([[0.09631843, 0.24500854, 0.46898283, 0.9108392 , 0.50174464],
       [0.882208  , 0.25147385, 0.5604017 , 0.31429226, 0.8818051 ],
       [0.4420753 , 0.67509234, 0.03215497, 0.51751751, 0.71041119]])

In [17]:
np.random.randn(3,5)

array([[ 1.16475462,  0.9265155 ,  2.70570619, -1.58254087, -0.73755809],
       [ 0.18515669, -0.6971215 , -0.54309971, -1.50113316, -1.61398391],
       [ 0.89854578, -0.24491559, -0.82610066,  0.52251995, -0.39113337]])

In [19]:
np.random.randint(1,100,(3,5))

array([[16, 45, 86, 91,  5],
       [82, 77, 83, 83, 81],
       [33, 48, 83, 24, 66]])

In [3]:
arr = np.ones(10)
b = arr*2

In [4]:
a  = b >2
print(a)

[False False False False False False False False False False]

In [5]:
print(b)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]

In [6]:
a = a+b
print(a)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]

In [7]:
a[a>0]

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [8]:
a[a<0]

array([], dtype=float64)

In [11]:
u = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
v = np.array([1, 0.5, 2, 1])
print(u)
print(v)

[[2 4 5 6]
 [1 2 1 2]
 [3 1 2 1]]
[1.  0.5 2.  1. ]

In [7]:
def matrix_vector_multiplication(u,v):
    result = np.full(u.shape[0],0.0)
    print(result)
    assert u.shape[1] == v.shape[0]
    for i in range(u.shape[0]):
        result[i] = 0
        for j in range(v.shape[0]):
            result[i] = result[i]+u[i][j]*v[j]
    return result
matrix_vector_multiplication(u,v)

[0. 0. 0.]

array([20. ,  6. ,  8.5])

In [8]:
v.shape[0]

4

In [12]:
u.shape[1]

4

In [17]:
u.dot(v)

array([20. ,  6. ,  8.5])

In [8]:
a = np.array([[1,1,2],[0,0.5,1],[0,2,1]])
I = np.eye(3) #generates identity matrix
prod = a.dot(I)
print(prod) #same as a

[[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]]

In [9]:
print(a)
print(a.shape)
ainv = np.linalg.inv(a)
print(ainv)
idmat = a.dot(ainv)
print(idmat)

[[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]]
(3, 3)
[[ 1.         -2.          0.        ]
 [ 0.         -0.66666667  0.66666667]
 [ 0.          1.33333333 -0.33333333]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [2]:
import pandas as pd
carData = [['BMW','XXX',1942,'Blue'],['Audi','YYY',1998,'Yellow'],['Swift','Desire',2000,'White'],['Hundai','Vernas',2010,'Black'],['Ambassador','ccc',2010,'Purple']]
header = ['Model','Make','Year','Color']
pd.DataFrame(carData,columns = header)

        Model    Make  Year   Color
0         BMW     XXX  1942    Blue
1        Audi     YYY  1998  Yellow
2       Swift  Desire  2000   White
3      Hundai  Vernas  2010   Black
4  Ambassador     ccc  2010  Purple

In [4]:
dictData = [{'Model':'BMW','Make':'XXX','Year':1942,'Color':'Blue'},{'Model':'Audi','Make':'YYY','Year':1998,'Color':'Yellow'},{'Model':'Swift','Make':'Desire','Year':2000,'Color':'White'},{'Model':'Hyundai','Make':'Vernas','Year':2010,'Color':'Black'},{'Model':'Ambassador','Make':'CCC','Year':2010,'Color':'purple'}]
df=pd.DataFrame(dictData)

In [6]:
df.Make

0       XXX
1       YYY
2    Desire
3    Vernas
4       CCC
Name: Make, dtype: str

In [7]:
df['Make']

0       XXX
1       YYY
2    Desire
3    Vernas
4       CCC
Name: Make, dtype: str

In [8]:
df[['Model','Make']]

        Model    Make
0         BMW     XXX
1        Audi     YYY
2       Swift  Desire
3     Hyundai  Vernas
4  Ambassador     CCC

Adding a column to a dataframe

In [13]:
df['id']=[1,2,3,4,5]
df

        Model    Make  Year   Color  id
0         BMW     XXX  1942    Blue   1
1        Audi     YYY  1998  Yellow   2
2       Swift  Desire  2000   White   3
3     Hyundai  Vernas  2010   Black   4
4  Ambassador     CCC  2010  purple   5

Deleting a column

In [14]:
del df['id']

In [15]:
df

        Model    Make  Year   Color
0         BMW     XXX  1942    Blue
1        Audi     YYY  1998  Yellow
2       Swift  Desire  2000   White
3     Hyundai  Vernas  2010   Black
4  Ambassador     CCC  2010  purple

In [16]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
df.index=['a','b','c','d','e']

In [18]:
df

        Model    Make  Year   Color
a         BMW     XXX  1942    Blue
b        Audi     YYY  1998  Yellow
c       Swift  Desire  2000   White
d     Hyundai  Vernas  2010   Black
e  Ambassador     CCC  2010  purple

In [19]:
df.loc[['c','d']]

     Model    Make  Year  Color
c    Swift  Desire  2000  White
d  Hyundai  Vernas  2010  Black

In [20]:
df.iloc[2] #use positional index to access the records

Model     Swift
Make     Desire
Year       2000
Color     White
Name: c, dtype: object

In [21]:
df.iloc[[2,3]]

     Model    Make  Year  Color
c    Swift  Desire  2000  White
d  Hyundai  Vernas  2010  Black

In [24]:
df = df.reset_index(drop=True) #changes the index back to 0,1,2,3 #creates a new dataframe with index reset to 0,1,2,3,4
df

        Model    Make  Year   Color
0         BMW     XXX  1942    Blue
1        Audi     YYY  1998  Yellow
2       Swift  Desire  2000   White
3     Hyundai  Vernas  2010   Black
4  Ambassador     CCC  2010  purple

Elementwise operation

In [25]:
df['Year']+2

0    1944
1    2000
2    2002
3    2012
4    2012
Name: Year, dtype: int64

In [26]:
df['Year']>=2000

0    False
1    False
2     True
3     True
4     True
Name: Year, dtype: bool

In [33]:
df[(df['Year']>=2000) & (df['Color'] == 'Black')] #filtering the records that meets certain conditions

     Model    Make  Year  Color
3  Hyundai  Vernas  2010  Black

String Operations

In [6]:
df['Make'].str.upper()

0       XXX
1       YYY
2    DESIRE
3    VERNAS
4       CCC
Name: Make, dtype: str

In [7]:
df

        Model    Make  Year   Color
0         BMW     XXX  1942    Blue
1        Audi     YYY  1998  Yellow
2       Swift  Desire  2000   White
3     Hyundai  Vernas  2010   Black
4  Ambassador     CCC  2010  purple

In [8]:
df['Year'].min()

np.int64(1942)

In [9]:
df.Year.max()

np.int64(2010)

In [10]:
df.describe()

              Year
count     5.000000
mean   1992.000000
std      28.495614
min    1942.000000
25%    1998.000000
50%    2000.000000
75%    2010.000000
max    2010.000000

In [11]:
df.Year.nunique()

4

In [12]:
df.isnull().sum()

Model    0
Make     0
Year     0
Color    0
dtype: int64

In [1]:
import pandas as pd
print(pd.__version__)

3.0.1